# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  
  - trigger: ":phdfull"
    replace: "Hi there,\nCurrently I have a fairly full lab, and am not recruiting new students directly.  However, I am happy to help advise students working primarily with other faculty in the department, so I encourage you to apply if there are other faculty you are also interested in.\nCheers,\nEd"
  
  - trigger: ":myzoom"
    replace: "https://ucsd.zoom.us/my/edvul"
  # Dates
  
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  
  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%H:%M"
  
  - trigger: ":dt"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
